name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./
        id: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: ${{ github.workspace }}/dist

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifacts

      - name: Deploy page
        uses: actions/deploy-pages@v1
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: build_artifacts
